name: Creative Junction
favicon: null
layout_spectrum: 0.49822
typography_spectrum: 0.49042
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#000000'
    - '#2a2a2a'
    - '#4c4c4c'
    - '#9a9a9a'
  brandStrength: 1
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
