name: Creative Junction
favicon: null
layout_spectrum: 1
typography_spectrum: 0.49042
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#203e59'
    - '#1e6daa'
    - '#508ebe'
    - '#bbd5e5'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
