name: Creative Junction
favicon: null
layout_spectrum: 0
typography_spectrum: 0.49042
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#f7d263'
    - '#76797c'
    - '#704319'
    - '#dea647'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
